version: 2.1

orbs:
  go: "circleci/go@1.7.1"

parameters:
  version:
    type: "string"
    default: "v5.0.1"
  run:
    type: "boolean"
    default: false

workflows:
  centaurid:
    when: << pipeline.parameters.run >>
    jobs:
      - build
      - publish:
          context: "github-context"
          requires:
            - build

jobs:
  build:
    executor:
      name: "go/default"
      tag: "1.21"
    resource_class: "large"
    steps:
      - checkout
      - run:
          name: "Install required system packages"
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends build-essential curl git musl-dev
      - run:
          name: "Clone Centauri"
          command: |
            git clone -b << pipeline.parameters.version >> https://github.com/notional-labs/composable-centauri
      - restore_cache:
          keys:
            - 'go-{{ checksum "composable-centauri/go.sum" }}'
      - run:
          name: "Build Centauri binary"
          command: |
            cd composable-centauri

            # Grab static libwasmvm
            wasmvm_version="$(go list -m all | grep -F "github.com/CosmWasm/wasmvm" | awk '{print $2}')"
            curl -JLO "https://github.com/CosmWasm/wasmvm/releases/download/${wasmvm_version}/libwasmvm_muslc.x86_64.a"
            ln -s libwasmvm_muslc.x86_64.a libwasmvm.x86_64.a

            make CC="x86_64-linux-musl-gcc" CGO_LDFLAGS="-L." LEDGER_ENABLED=false LINK_STATICALLY=true build

            # Smoke test
            ldd ./bin/centaurid || :
            ./bin/centaurid version --long
      - save_cache:
          key: 'go-{{ checksum "composable-centauri/go.sum" }}'
          paths:
            - "~/go"
      - persist_to_workspace:
          root: "./composable-centauri/bin"
          paths:
            - "centaurid"
  publish:
    executor:
      name: "go/default"
      tag: "1.17"
    steps:
      - checkout
      - attach_workspace:
          at: '/tmp/binaries'
      - run:
          name: "Install GHR"
          command: go get github.com/tcnksm/ghr
      - run:
          name: "Publish Github release"
          command: |
            ghr -t "${GITHUB_TOKEN}" \
              -n "<< pipeline.parameters.version >>" \
              -b "For changes, see here: https://github.com/notional-labs/composable-centauri/releases/tag/<< pipeline.parameters.version >>" \
              -recreate "<< pipeline.parameters.version >>" \
              /tmp/binaries/centaurid
